name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - graphviz
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - xgboost
    - matplotlib
    - plotly
    - sklearn
    - scipy
    - keras
    - pydot
    - fbprophet
    - bokeh
    - urllib3
    - seaborn
